// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtC7yW4ik6PtMLIm02EmufGRRpmVNmwAg',
    appId: '1:777557076981:web:0f9cf51401002216788ebc',
    messagingSenderId: '777557076981',
    projectId: 'auth-a1718',
    authDomain: 'auth-a1718.firebaseapp.com',
    storageBucket: 'auth-a1718.firebasestorage.app',
    measurementId: 'G-KZDF7XZ5D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDczG6YOQFihXQLBAxT2ejw9WBiDOrarxc',
    appId: '1:777557076981:android:7ff60e69b166cfe2788ebc',
    messagingSenderId: '777557076981',
    projectId: 'auth-a1718',
    storageBucket: 'auth-a1718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRn-KHIZflSqZrQA-EUtek6ThRn5u9toI',
    appId: '1:777557076981:ios:c3d932aa2b0dd60f788ebc',
    messagingSenderId: '777557076981',
    projectId: 'auth-a1718',
    storageBucket: 'auth-a1718.firebasestorage.app',
    iosBundleId: 'com.example.authClone',
  );
}
